name: Build Site
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest    
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Work...
      run:
        echo 'Hello owner'
